# https://taskfile.dev
version: '3'
tasks:
  install-truffle:
    cmds:
    # node --version
    - npm install -g truffle -ddd
    - truffle version

    # $ truffle version
    # Truffle v5.9.0 (core: 5.9.0)
    # Ganache v7.8.0
    # Solidity - 0.8.13 (solc-js)
    # Node v18.16.0
    # Web3.js v1.10.0
